# Системы линейных уравнений. Часть 1

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Путем элементарных преобразований постараемся привести матрицу к ступенчатому виду.

Вычтем из второй строки первую, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строки первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

В полученном ступенчатом виде мы имеем ступеньки из двух чисел. В таком случае система имеет _бесконечное количество решений._

Оставшаяся матрица соответствует системе:  
$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

Неизвестные, «сидящие» на ступеньках матрицы, принято назывть _базисными_, и их нужно выразить через _свободные_ неизвестные. В данном случае можно рассматривать в качестве _свободного_ параметра $x_{3}=c$. Тогда, выражая остальные переменные через $c$, получим:

$$x_{4}=c$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=(3c-4)/2$$
$$-x_{2} + (3c-4)/2 + 5c=-2 \; \Leftrightarrow \; x_{2}=-13c/2$$
$$x_{1} - 13c/2 - (3c-4)/2 - 2c=0 \; \Leftrightarrow \; x_{1}=10c-2.$$

Таковым будет _общее решение системы_. Подставляя произвольные числа вместо $c$, мы получим _частное решение_. Например, при $c=0$:

$$x_{1}=0,$$
$$x_{2}=-2,$$
$$x_{3}=-2$$
$$x_{4}=0$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

Необходимым и достаточным условием совместности системы из $m$ уравнений с $n$ неизвестными является равенство между собой рангов матрицы коэффициентов $A$ и расширенной матрицы $\tilde A$  
Причем:<br>
1) если $rankA=rank \tilde A=n$, где $n$ — число неизвестных, то система определена, т. е. имеет единственное решение;<br>
2) если $rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>
3) если $rankA<rank \tilde A$, то система несовместна.


а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

Запишем матрицу коэффициентов А
$${A}=\begin{pmatrix}
3 & -1 & 1 \\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{pmatrix}.$$

И расширенную матрицу:  
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}.$$  
Ранг матрицы коэффициентов равен 3 и ранг расширенной матрицы равен трем, т.к. нет линейно зависимых строк.   
$rankA=rank \tilde A=n$ решение единественное.

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Запишем матрицу коэффициентов А
$${A}=\begin{pmatrix}
2 & -4 & 6 \\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{pmatrix}.$$

И расширенную матрицу:  
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3\\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}.$$  
Ранг матрицы коэффициентов равен 1, т.к. первая строка это вторая умноженная на 2. А третья строка это вторая строка умноженная на 3.  
Ранг расширенной матрицы равен трем, т.к. нет линейно зависимых строк.   
$rankA<rank \tilde A$, то система несовместна.

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

Запишем матрицу коэффициентов А
$${A}=\begin{pmatrix}
1 & 2 & 5 \\ 
3 & 1 & -8\\ 
\end{pmatrix}.$$

И расширенную матрицу:  
$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8\\ 
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}.$$  
Ранг матрицы коэффициентов равен 2, т.к. нет линейно зависимых сток.
Ранг расширенной матрицы равен 2, т.к. нет линейно зависимых строк. 
Количество неизвестных равно 3.  
$rankA=rank \tilde A<n$, то система имеет бесконечное количество решений;<br>

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$



Т.к. в матрице коэффициентов и в расширенной матрице нет линейно зависимых строк.
Количество неизвестных равно 4.  
$rankA=rank \tilde A=n$ решение единественное.

Проверим на питоне

In [3]:
import numpy as np
A_3 = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 1]])
r_3 = np.linalg.matrix_rank(A_3)
print(f'Матрица:\n{A_3}')
print(f'Ранг матрицы: {r_3}')

Матрица:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  1]]
Ранг матрицы: 4


In [4]:
import numpy as np
A_3_extend = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 1, 1]])
r_3_extend = np.linalg.matrix_rank(A_3)
print(f'Матрица:\n{A_3_extend}')
print(f'Ранг матрицы: {r_3_extend}')

Матрица:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  1  1]]
Ранг матрицы: 4


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Т.к. в матрице коэффицентов вторая строка получается прибавлением к элементам первой строки 3.
А третья строка получается прибавлением к элементам первой строки 6. Ранг матрицы коэффициентов равен 1. Чтобы система была несовместной необходимо чтобы  𝑟𝑎𝑛𝑘𝐴<𝑟𝑎𝑛𝑘𝐴̃  .
Это можно получить, если разница между элементами  𝑎  и  𝑏  не будет равна 3, или разница между элементами  𝑎  и  𝑐  не будет равна 6.

# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4 \\ 
\end{vmatrix} = -2$$

$$detA_{1}=\begin{vmatrix}
1 & -2 \\ 
7 & -4 \\ 
\end{vmatrix} = -10$$

$$detA_{2}=\begin{vmatrix}
1 & 1 \\ 
3 & 7 \\ 
\end{vmatrix} = -4$$

$$x_{1} = \frac{detA_{1}}{detA} = \frac{-2}{-10}=0.2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-2}{-4}=0.5,$$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+5
\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=43\neq 0$$

следовательно, система совместна.

Найдем определители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}+
5\begin{vmatrix}
-2 & 1 \\ 
1 & 4
\end{vmatrix}=86$$

$$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
2\begin{vmatrix}
-2 & -3\\ 
1 & 1 
\end{vmatrix}-
10\begin{vmatrix}
1 & -3\\ 
2 & 1 
\end{vmatrix}+5
\begin{vmatrix}
1 & -2 \\ 
2 & 1
\end{vmatrix}=-43$$

$$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -2\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
1 & -2\\ 
2 & 1 
\end{vmatrix}+
10\begin{vmatrix}
1 & 1 \\ 
2 & 4
\end{vmatrix}=43$$

Найдем решение по формулам Крамера:

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

Прозведем проверку с помощью python

In [9]:
import numpy as np
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


In [10]:
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'Матрица:\n{a1}')
print(f'Определитель:\n{np.linalg.det(a1):.0f}')

Матрица:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель:
86


In [11]:
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'Матрица:\n{a2}')
print(f'Определитель:\n{np.linalg.det(a2):.0f}')

Матрица:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель:
-43


In [12]:
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица:\n{a3}')
print(f'Определитель:\n{np.linalg.det(a3):.0f}')

Матрица:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель:
43


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

a) Начнем прямой ход метода Гаусса. Для этого домножим первую строку на $2$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $2$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $3$. Значит, в матрицу $L$ запишем $l_{31}=3$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 14 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{32} & 1
\end{pmatrix}$$

Далее умножим вторую строку на $10/7$ и вычтем ее из третьей. При этом в матрицу $L$ на место $l_{32}$ запишем $10/7$.

В итоге получим

$$U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 14 & 4 \\ 
0 & 0 & -16.2
\end{pmatrix}$$

$$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 10/7 & 1
\end{pmatrix}$$

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$



Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=3,$$

$$l_{22}=\sqrt{a_{22}-u_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=0.2\left ( 15 - (-5)\cdot 5 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-82.5,$$

$$y_{3}=21.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-82.5, \\
3x_{3}=21.
\end{cases}$$

$$x_{3}=7,$$

$$x_{2}=-19.3,$$

$$x_{1}=-8.06.$$