# Матрицы и матричные операции. Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

Число столбцов первой матрицы не равно числу строк во второй матрице

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

Результат -  матрица 2х3

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

Результат - матрица 8х8

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.   

Результат - матрица 4х4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



In [10]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A

array([[ 1, -2],
       [ 3,  0]])

In [7]:
B

array([[ 4, -1],
       [ 0,  5]])

In [8]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [9]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


In [11]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
A

array([[ 1,  7],
       [ 3, -6]])

In [12]:
B

array([[ 0,  5],
       [ 2, -1]])

In [13]:
C

array([[ 2, -4],
       [ 1,  1]])

In [6]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.



In [15]:
A4 = np.array([[4, 1], [5, -2], [2, 3]])
A4_T = np.transpose(A4)
A4

array([[ 4,  1],
       [ 5, -2],
       [ 2,  3]])

In [16]:
A4_T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [10]:
np.dot(A4, A4_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [11]:
np.dot(A4_T, A4)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

# Матрицы и матричные операции. Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx*sinx-(-cosx)*cosx = sinx^2+cosx^2=1
$$

б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [12]:
L = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{L}')
print(f'Определитель:\n{np.linalg.det(L)}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180.0


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


In [13]:
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{F}')
print(f'Определитель:\n{np.linalg.det(F)}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-9.51619735392994e-16


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = det (A*A) = det(A) * det (A) = 4*4 = 16$;
    
   б) $det(A^{T}) = det(A) = 4$;
    
   в) $det(2A)= 2*4 = 8$.
   


__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



In [22]:
A1 = np.array([[-2, 7, -3], [4, -14, 6], [-3, -7, 13]])
np.linalg.det(A1)

0.0

Т.к. определитель равен 0 матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [23]:
A4 = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(A4)
A4

array([[1, 2, 3],
       [1, 1, 1],
       [2, 3, 4]])

In [24]:
r

2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [25]:
Z = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(Z)
Z

array([[0, 0, 2, 1],
       [0, 0, 2, 2],
       [0, 0, 4, 3],
       [2, 3, 5, 6]])

In [26]:
r

3