__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [4]:
import numpy as np
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)
A

array([[-1, -6],
       [ 2,  6]])

Собственные значения:

In [10]:
w

array([2., 3.])

Собственные векторы

In [11]:
v

array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]])

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$$A=-1\cdot\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}$$  
Оператор повората равен  
$$A = -1\cdot \textbf{I}$$
$$det(\textbf{A}-\lambda\textbf{I})=0$$
$$det(-1\cdot \textbf{I}-\lambda\textbf{I})=0$$
Находим, что $\lambda = -1$  
Т.к. при умножении любого вектора x на единичную матрицу, мы получаем вектор x
$$-1\cdot \textbf{I}x=\lambda x.$$
Подставим в это выражение значение $\lambda$:  
$$-1\cdot x=-1 \cdot x.$$
Отсюда следует, что любой вектор умноженный на оператор поворота, будет для него собственным.

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Вектор $x=(1,1)$ является собственным вектором линейного оператора, заданного матрицей $A$.

__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix} \cdot 
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}  =
\lambda \cdot
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix} $$


$$\begin{cases}
-9=3\cdot\lambda \\ 
9 = -3 \cdot \lambda\\
-12 = -4 \cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\ 
\lambda=3
\end{cases}.$$

Такая система не имеет смысла, следовательно, вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.