1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [2]:
import numpy as np
A = np.array([[1, 2, 0], [0, 0 , 5], [3, -4, 2] ,[1, 6, 5], [0, 1, 0]])
A

array([[ 1,  2,  0],
       [ 0,  0,  5],
       [ 3, -4,  2],
       [ 1,  6,  5],
       [ 0,  1,  0]])

In [5]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

array([[8.82486885, 0.        , 0.        ],
       [0.        , 6.14060608, 0.        ],
       [0.        , 0.        , 2.53271528],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [6]:
U

array([[ 0.17056501,  0.15680918, -0.53077508, -0.79905375, -0.16158397],
       [ 0.39287016, -0.52933945,  0.6134793 , -0.43375771,  0.03082495],
       [-0.14366152, -0.82449256, -0.52379105,  0.14049848,  0.07400343],
       [ 0.88843702,  0.06074346, -0.24655277,  0.37755832, -0.06042632],
       [ 0.08125046,  0.10831843, -0.08231425, -0.10524851,  0.98173958]])

In [12]:
# Убедимся, что она действительно ортогональна
# np.set_printoptions(precision=1)
np.set_printoptions(suppress=True)
print(np.dot(U.T, U))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [13]:
V

array([[ 0.1, -0.4, -0.9],
       [ 0.7,  0.7, -0.2],
       [ 0.7, -0.7,  0.3]])

In [14]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [15]:
# Проведем проверку
np.set_printoptions(suppress=True)
print(f'{np.dot(np.dot(U, D), V.T)}')

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


2. Для матрицы из предыдущего задания найти:

а) евклидову норму

In [17]:
D[0, 0]

8.824868854820442

б) норму Фробениуса.

In [19]:
np.linalg.norm(A, 'fro')

11.045361017187261